### ISSUE TITLE
Issue: Fix CLA workflow

### ISSUE THREAD

**Issue by strbit** [jarsft/.github#12]
### Describe the issue

Upon execution, the CLA workflow fails to create a temporary token to use, possibly due to a lack of permissions.

### Reproduction

Create a pull-request to trigger the CLA workflow.

### Workbench information

```shell
ubuntu-latest (gh-action)
```

### Additional information

Workflow error stack:

```
Error: Error: Error message: Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable
    at OidcClient.<anonymous> (file:///home/runner/work/_actions/qoomon/actions--access-token/v3/action/dist/main.js:581:23)
    at Generator.next (<anonymous>)
    at file:///home/runner/work/_actions/qoomon/actions--access-token/v3/action/dist/main.js:518:71
    at new Promise (<anonymous>)
    at __webpack_modules__.8041.__awaiter (file:///home/runner/work/_actions/qoomon/actions--access-token/v3/action/dist/main.js:514:12)
    at OidcClient.getIDToken (file:///home/runner/work/_actions/qoomon/actions--access-token/v3/action/dist/main.js:567:16)
    at Object.<anonymous> (file:///home/runner/work/_actions/qoomon/actions--access-token/v3/action/dist/main.js:419:46)
    at Generator.next (<anonymous>)
    at file:///home/runner/work/_actions/qoomon/actions--access-token/v3/action/dist/main.js:131:71
    at new Promise (<anonymous>)
Error: Error message: Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable
```

### Submission checklist

- [X] Follow the [Code of Conduct](https://github.com/jarsft/.github/blob/production/CODE_OF_CONDUCT.md)
- [X] Read the [Contribution Guide](https://github.com/jarsft/.github/blob/production/CONTRIBUTING.md)
- [X] Check that no issue that reports the same bug exists.
- [X] Check that this is a concrete bug.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] Double-checked that the issue is descriptive & concise.

### Optional contributions

- [X] I am willing to submit a PR to fix this issue.
- [ ] I am willing to submit an unfinished/unstable PR. (failing tests, etc.)

**Comment by strbit** [comment]
Not fully fixed, reopening.
